name: Generate

on:
  repository_dispatch:
    types: [generate-sdk]

env:
  PACKAGE_NAME: freee/freee-accounting-sdk
  SCHEMA_URL_TEMP: https://gist.githubusercontent.com/shibayan/3fdf5a66554e5e7ccfe4cc8350db86d7/raw/64548c7ad8bb4c65c0bbe1748ca8f759da648aa6/api-schema.yml
  KEEP_CURRENT_HEADER_SELECTOR: true

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - name: Check client_payload
      if: ${{ ! github.event.client_payload.origin_ref }}
      run: exit 1

    - uses: actions/github-script@v2
      if: ${{ contains(github.event.client_payload.origin_ref, 'refs/tags/') }}
      id: release_tag
      with:
        result-encoding: string
        script: |
          const { origin_ref } = context.payload.client_payload
          const words = origin_ref.split('/')
          return words[2]

    - name: Install packages
      run: |
        sudo snap install yq

    - uses: actions/checkout@v2

    - name: Remove old codes
      run: |
        rm -rf .openapi-generator/VERSION docs lib test .php_cs .travis.yml git_push.sh phpunit.xml.dist

    - name: Update lib version
      run: |
        yq write -i .openapi-generator/config.yml artifactVersion v2.0.0-test

    - name: Generate APIs
      env:
        SCHEMA_URL: https://raw.githubusercontent.com/freee/freee-api-schema/${{ steps.release_tag.outputs.result }}/v2020_06_15/open-api-3/api-schema.yml
      run: |
        docker run --rm -u "$(id -u $USER):$(id -g $USER)" -v "${PWD}:/local" openapitools/openapi-generator-cli:latest-release generate \
          -i ${{ env.SCHEMA_URL_TEMP }} \
          -c /local/.openapi-generator/config.yml \
          -g php \
          -o /local/
        rm -rf .travis.yml git_push.sh generate.log
        mv -f README.md README_auto-generated.md
        sed -i -e 's#"freee/freee-accounting-sdk-php"#"${{ env.PACKAGE_NAME }}"#g' README_auto-generated.md
        git checkout README.md

    - name: Maintain composer.json
      run: |
        cat composer.json | jq --indent 4 '. | .name = "${{ env.PACKAGE_NAME }}" | .type = "library" | .description = "Accounting freee PHP SDK" | .keywords += ["freee"] | .homepage = "https://developer.freee.co.jp/" | .license = "MIT" | .authors[0].name = "Freee" | .authors[0].homepage = "https://developer.freee.co.jp/"' > composer.json.tmp
        mv -f composer.json.tmp composer.json

    - name: Revert HeaderSelector
      if: ${{ env.KEEP_CURRENT_HEADER_SELECTOR }}
      run: |
        git checkout lib/HeaderSelector.php

    - name: Git
      run: |
        git stash push .openapi-generator/config.yml
        git fetch
        git checkout master
        git config --local user.name "API Generator"
        git stash pop
        git add .
        git commit -m "Generated by release ${{ steps.release_tag.outputs.result }}"
        git reset --hard HEAD
        git clean -fdx

    - name: Create pull request
      uses: peter-evans/create-pull-request@v3